services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: steven11
      POSTGRES_DB: algorithm_visualiser
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:steven11@db/algorithm_visualiser
    depends_on:
      - db

volumes:
  pgdata: